### ISSUE TITLE
Who will bear the responsibility of invoking Article 50?

### ISSUE THREAD

**Issue by MrHash** [rooreynolds/hasarticle50beeninvoked#1]

**Comment by mhaehnel** [comment]
The people. They voted for it.

**Comment by rooreynolds** [comment]
The House Of Commons Library published [this research briefing on the process of leaving the EU](http://researchbriefings.parliament.uk/ResearchBriefing/Summary/CBP-7551). In its view

> "After a vote to leave the EU, the Prime Minister would notify the European Council of the UK’s intention to withdraw.
> 
> Notification would be a political decision. Legally, the referendum is not binding, although it would probably be considered politically binding."

**Comment by MrHash** [comment]
I think this is still an open issue. To invoke the withdrawal could lead to the de-unification of the UK and it is unclear who will bear the responsibility of that unintended outcome now that Cameron has given it away.

**Comment by rooreynolds** [comment]
Oh, I see what you mean. 

I think it's outside the scope of this repository to answer the question, and I will rely on common sense and popular opinion (um, mainstream media reporting probably) to guide me in knowing when it does get invoked.

I've updated the readme to link to a useful parliamentary briefing paper. Constitutional experts are still getting their heads around the implications and likely sequences of events.
